Add ChipsView
ciandt-d1/dragonfly-android pull request #44
Opened 2017-06-13 17:36 UTC by jeanpimentel

2017-06-13 18:10 UTC, ivamluz requested changes

2017-06-13 18:10 UTC, ivamluz commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/ChipAdapter.kt
> +    private var layout = -1
What about defining a UNINITIALIZED_LAYOUT_RESOURCE = -1?

2017-06-13 18:10 UTC, ivamluz commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/ChipAdapter.kt
> +        if (button == null || button !is Button) {
What about casting to Button directly when we findViewById()? The if statement would be simpler, no?

2017-06-13 18:10 UTC, ivamluz commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/ChipsView.kt
> +        val inflater = context.getSystemService(Context.LAYOUT_INFLATER_SERVICE) as LayoutInflater
What about adding an extension function to Context?

`context.getLayoutInflaterService()`

2017-06-13 18:10 UTC, ivamluz commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/ChipsView.kt
> +            if (chipLayout != -1) {
Is -1 the UNINITIALIZED_LAYOUT_RESOURCE proposed above? If so, I think it's clear with a const.

2017-06-13 18:10 UTC, ivamluz commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/ChipsView.kt
> +        adapter.notifyItemInserted(chips.size - 1)
If an empty list is passed, notifiyItemInserted(-1) will be called, right? Is this expected?

2017-06-13 18:10 UTC, ivamluz commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/ChipsView.kt
> +    private fun dpToPx(dp: Int): Int = (dp * Resources.getSystem().displayMetrics.density).toInt()
What about this as an extension function to View or another framework class? Feels like a potentially reusable logic.

2017-06-13 18:10 UTC, ivamluz commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/SpaceItemDecoration.kt
> +            val lastPosition = it.adapter.itemCount - 1
Any problem if itemCount is 0?

2017-06-13 18:10 UTC, ivamluz commented on app/src/main/res/layout/component_chips_view.xml
> +        android:layout_alignTop="@+id/list"
These should be @id instead, no? Same for alignBottom below.

2017-06-13 18:10 UTC, ivamluz commented on app/src/main/res/layout/component_chips_view.xml
> +        android:layout_alignTop="@+id/list"
Same about @id.

2017-06-13 18:25 UTC, jeanpimentel commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/ChipAdapter.kt
> +    private var layout = -1
Done

2017-06-13 18:29 UTC, jeanpimentel commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/ChipAdapter.kt
> +        if (button == null || button !is Button) {
Done

```
val button = view.findViewById(R.id.chipButton) as Button?
if (button != null) {
    throw IllegalArgumentException("Layout for item should contain a Button with id = button")
}

2017-06-13 18:34 UTC, ivamluz commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/ChipAdapter.kt
> +        if (button == null || button !is Button) {
Should be if button == null, no?

2017-06-13 18:45 UTC, jeanpimentel commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/ChipsView.kt
> +        val inflater = context.getSystemService(Context.LAYOUT_INFLATER_SERVICE) as LayoutInflater
Done

2017-06-13 18:57 UTC, jeanpimentel commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/ChipsView.kt
> +            if (chipLayout != -1) {
Done

2017-06-13 19:10 UTC, jeanpimentel commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/ChipsView.kt
> +    private fun dpToPx(dp: Int): Int = (dp * Resources.getSystem().displayMetrics.density).toInt()
Done

2017-06-13 19:31 UTC, jeanpimentel commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/ChipsView.kt
> +        adapter.notifyItemInserted(chips.size - 1)
Wrong method. This should be notifyDataSetChanged

2017-06-13 19:34 UTC, jeanpimentel commented on app/src/main/java/com/ciandt/dragonfly/example/components/chips/SpaceItemDecoration.kt
> +            val lastPosition = it.adapter.itemCount - 1
No problem, because it wont be rendered but I changed

2017-06-13 19:40 UTC, jeanpimentel commented on app/src/main/res/layout/component_chips_view.xml
> +        android:layout_alignTop="@+id/list"
I usually use @+id to avoid circular dependencies and order problems, but in this case it isnt a problem. Changed.

2017-06-13 19:41 UTC, jeanpimentel commented
@ivamluz Changed

2017-06-13 20:17 UTC, ivamluz approved these changes
Approved with a suggestion.

2017-06-13 20:17 UTC, ivamluz commented on app/src/main/java/com/ciandt/dragonfly/example/infrastructure/extensions/Int+Extension.kt
> +fun Int.toPx(): Int = (this * Resources.getSystem().displayMetrics.density).toInt()
I think px(), instead of toPx() is better. Just a suggestion... (same for toDp())

2017-06-13 20:23 UTC, jeanpimentel commented on app/src/main/java/com/ciandt/dragonfly/example/infrastructure/extensions/Int+Extension.kt
> +fun Int.toPx(): Int = (this * Resources.getSystem().displayMetrics.density).toInt()
Arguments:

- Best semantics
1.px() sounds like 1px, and not 1dp converted to px

- Keep the pattern
```
fun toByte(): Byte
fun toChar(): Char
fun toShort(): Short
fun toInt(): Int
fun toLong(): Long
fun toFloat(): Float
fun toDouble(): Double
```

makes sense?

2017-06-14 12:07 UTC, ivamluz commented on app/src/main/java/com/ciandt/dragonfly/example/infrastructure/extensions/Int+Extension.kt
> +fun Int.toPx(): Int = (this * Resources.getSystem().displayMetrics.density).toInt()
Makes :+1:

2017-06-14 12:26 UTC, merged